### PR TITLE
Maja whitelist feature

### PR DESCRIPTION
**Pull request by MajaSchermuly**
This PR introduces the new whitelist table in the database. This is the first part of the user story below
Jira : https://carpool-request-service.atlassian.net/browse/CRS-28

Criteria Hit:
 - create entity whitelist
 - create admin level page with add/edit/remove features for emails in whitelist table

### CODE REVIEW

**Comment by murbina7631** [comment]
To start, the branch to merge is failing, so please fix that. I believe it has to do with the auto generated test cases, so go ahead and delete those.

**Comment by murbina7631** [comment]
Could you edit the migration file to look more like the others, adding a primary key attribute and an "Id: false" to the migration file.

**Comment by murbina7631** [comment]
Please double check that the scaffold css file hasn't overwritten any of joseph's changes too, as scaffold creation will do that

**Comment by MajaSchermuly** [comment]
I implemented the requested changes the the .css changes did not interfere with the UI css Joseph implemented

**Comment by murbina7631** [comment]
Alright, thanks for making the requested changes, everything looks good now

**Comment by murbina7631** [comment]
The coding standards were passed by RuboCop.

Code is well documented well.

**Pull request merged**
